all:
	cd nested/cuda; make
	cd nested/cl; make
	cd simple/cuda; make
	cd simple/cl; make

clean:
	cd nested/cuda; make clean
	cd nested/cl; make clean
	cd simple/cuda; make clean
	cd simple/cl; make clean
